name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  forbidden-word-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fail if forbidden word exists
        run: |
          if grep -R "password" . \
            --exclude-dir=.git \
            --exclude-dir=.github; then
            echo "‚ùå Forbidden word found"
            exit 1
          else
            echo "‚úÖ Clean code"
          fi

  deploy:
    needs: forbidden-word-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simulate deployment
        run: |
          echo "üöÄ Deploying application..."
          echo "Deployment successful"
